language: cpp

env:
  - CTEST_OUTPUT_ON_FAILURE=ON

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake

before_script:
  - cmake . -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX}

script:
  - make
  - make test
