version: '{build}'

configuration:
  - RelWithDebInfo

install:
  - appveyor DownloadFile https://github.com/Zeex/pawn/releases/download/20150412/pawnc-3.10.20150412-windows.zip
  - 7z x pawnc-3.10.20150412-windows.zip
  - set PATH=%PATH%;%CD%\pawnc-3.10.20150412-windows\bin

  - appveyor DownloadFile https://www.dropbox.com/s/9b5wca29x8uc9yi/samp03z_svr_R4_win32.zip?dl=1
  - 7z x samp03z_svr_R4_win32.zip
  - set SAMP_SERVER_ROOT=%CD%

  - set PATH=%PATH%;C:\Python27\Scripts
  - pip install samp-server-cli

before_build:
  - cmake . -G "Visual Studio 10 2010"

build_script:
  - cmake --build . --config %CONFIGURATION%
  - cmake --build . --config %CONFIGURATION% --target package

test_script:
  - ctest --build-config %CONFIGURATION%

artifacts:
  - path: crashdetect-*-win32.zip
    name: Binaries

on_failure:
  - type Testing\Temporary\LastTest.log

deploy:
  description: '<Put release description here>'
  provider: GitHub
  auth_token:
    secure: ++mk9GhXTpN/hdVjIIi/nHpu0gYpDybMJNDPB3lld8r1UyfoPbz08SVGeSS84HjR
  artifact: /crashdetect-.*-win32\.zip/
  draft: true
  on:
    appveyor_repo_tag: true
