// Copyright (c) 2013-2015 Zeex
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice,
//    this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright notice,
//    this list of conditions and the following disclaimer in the documentation
//    and/or other materials provided with the distribution.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.

#ifndef AMXOPCODE_H
#define AMXOPCODE_H

#include <array>
#include <string_view>

#include <amx/amx.h>

using namespace std::string_view_literals;

enum AMXOpcode {
  AMX_OP_NONE,         AMX_OP_LOAD_PRI,     AMX_OP_LOAD_ALT,
  AMX_OP_LOAD_S_PRI,   AMX_OP_LOAD_S_ALT,   AMX_OP_LREF_PRI,
  AMX_OP_LREF_ALT,     AMX_OP_LREF_S_PRI,   AMX_OP_LREF_S_ALT,
  AMX_OP_LOAD_I,       AMX_OP_LODB_I,       AMX_OP_CONST_PRI,
  AMX_OP_CONST_ALT,    AMX_OP_ADDR_PRI,     AMX_OP_ADDR_ALT,
  AMX_OP_STOR_PRI,     AMX_OP_STOR_ALT,     AMX_OP_STOR_S_PRI,
  AMX_OP_STOR_S_ALT,   AMX_OP_SREF_PRI,     AMX_OP_SREF_ALT,
  AMX_OP_SREF_S_PRI,   AMX_OP_SREF_S_ALT,   AMX_OP_STOR_I,
  AMX_OP_STRB_I,       AMX_OP_LIDX,         AMX_OP_LIDX_B,
  AMX_OP_IDXADDR,      AMX_OP_IDXADDR_B,    AMX_OP_ALIGN_PRI,
  AMX_OP_ALIGN_ALT,    AMX_OP_LCTRL,        AMX_OP_SCTRL,
  AMX_OP_MOVE_PRI,     AMX_OP_MOVE_ALT,     AMX_OP_XCHG,
  AMX_OP_PUSH_PRI,     AMX_OP_PUSH_ALT,     AMX_OP_PUSH_R,
  AMX_OP_PUSH_C,       AMX_OP_PUSH,         AMX_OP_PUSH_S,
  AMX_OP_PAMX_OP_PRI,  AMX_OP_PAMX_OP_ALT,  AMX_OP_STACK,
  AMX_OP_HEAP,         AMX_OP_PROC,         AMX_OP_RET,
  AMX_OP_RETN,         AMX_OP_CALL,         AMX_OP_CALL_PRI,
  AMX_OP_JUMP,         AMX_OP_JREL,         AMX_OP_JZER,
  AMX_OP_JNZ,          AMX_OP_JEQ,          AMX_OP_JNEQ,
  AMX_OP_JLESS,        AMX_OP_JLEQ,         AMX_OP_JGRTR,
  AMX_OP_JGEQ,         AMX_OP_JSLESS,       AMX_OP_JSLEQ,
  AMX_OP_JSGRTR,       AMX_OP_JSGEQ,        AMX_OP_SHL,
  AMX_OP_SHR,          AMX_OP_SSHR,         AMX_OP_SHL_C_PRI,
  AMX_OP_SHL_C_ALT,    AMX_OP_SHR_C_PRI,    AMX_OP_SHR_C_ALT,
  AMX_OP_SMUL,         AMX_OP_SDIV,         AMX_OP_SDIV_ALT,
  AMX_OP_UMUL,         AMX_OP_UDIV,         AMX_OP_UDIV_ALT,
  AMX_OP_ADD,          AMX_OP_SUB,          AMX_OP_SUB_ALT,
  AMX_OP_AND,          AMX_OP_OR,           AMX_OP_XOR,
  AMX_OP_NOT,          AMX_OP_NEG,          AMX_OP_INVERT,
  AMX_OP_ADD_C,        AMX_OP_SMUL_C,       AMX_OP_ZERO_PRI,
  AMX_OP_ZERO_ALT,     AMX_OP_ZERO,         AMX_OP_ZERO_S,
  AMX_OP_SIGN_PRI,     AMX_OP_SIGN_ALT,     AMX_OP_EQ,
  AMX_OP_NEQ,          AMX_OP_LESS,         AMX_OP_LEQ,
  AMX_OP_GRTR,         AMX_OP_GEQ,          AMX_OP_SLESS,
  AMX_OP_SLEQ,         AMX_OP_SGRTR,        AMX_OP_SGEQ,
  AMX_OP_EQ_C_PRI,     AMX_OP_EQ_C_ALT,     AMX_OP_INC_PRI,
  AMX_OP_INC_ALT,      AMX_OP_INC,          AMX_OP_INC_S,
  AMX_OP_INC_I,        AMX_OP_DEC_PRI,      AMX_OP_DEC_ALT,
  AMX_OP_DEC,          AMX_OP_DEC_S,        AMX_OP_DEC_I,
  AMX_OP_MOVS,         AMX_OP_CMPS,         AMX_OP_FILL,
  AMX_OP_HALT,         AMX_OP_BOUNDS,       AMX_OP_SYSREQ_PRI,
  AMX_OP_SYSREQ_C,     AMX_OP_FILE,         AMX_OP_LINE,
  AMX_OP_SYMBOL,       AMX_OP_SRANGE,       AMX_OP_JUMP_PRI,
  AMX_OP_SWITCH,       AMX_OP_CASETBL,      AMX_OP_SWAP_PRI,
  AMX_OP_SWAP_ALT,     AMX_OP_PUSH_ADR,     AMX_OP_NOP,
  AMX_OP_SYSREQ_N,     AMX_OP_SYMTAG,       AMX_OP_BREAK,
  AMX_OP_PUSH2_C,      AMX_OP_PUSH2,        AMX_OP_PUSH2_S,
  AMX_OP_PUSH2_ADR,    AMX_OP_PUSH3_C,      AMX_OP_PUSH3,
  AMX_OP_PUSH3_S,      AMX_OP_PUSH3_ADR,    AMX_OP_PUSH4_C,
  AMX_OP_PUSH4,        AMX_OP_PUSH4_S,      AMX_OP_PUSH4_ADR,
  AMX_OP_PUSH5_C,      AMX_OP_PUSH5,        AMX_OP_PUSH5_S,
  AMX_OP_PUSH5_ADR,    AMX_OP_LOAD_BOTH,    AMX_OP_LOAD_S_BOTH,
  AMX_OP_CONST,        AMX_OP_CONST_S,      AMX_OP_SYSREQ_D,
  AMX_OP_SYSREQ_ND,    AMX_OP_LAST_
};

const int NUM_AMX_OPCODES = AMX_OP_LAST_;

cell RelocateAMXOpcode(cell opcode);

constexpr std::array<std::string_view, NUM_AMX_OPCODES> AMXOpcodeNames = {
  "OP_NONE"sv,
  "OP_LOAD_PRI"sv,
  "OP_LOAD_ALT"sv,
  "OP_LOAD_S_PRI"sv,
  "OP_LOAD_S_ALT"sv,
  "OP_LREF_PRI"sv,
  "OP_LREF_ALT"sv,
  "OP_LREF_S_PRI"sv,
  "OP_LREF_S_ALT"sv,
  "OP_LOAD_I"sv,
  "OP_LODB_I"sv,
  "OP_CONST_PRI"sv,
  "OP_CONST_ALT"sv,
  "OP_ADDR_PRI"sv,
  "OP_ADDR_ALT"sv,
  "OP_STOR_PRI"sv,
  "OP_STOR_ALT"sv,
  "OP_STOR_S_PRI"sv,
  "OP_STOR_S_ALT"sv,
  "OP_SREF_PRI"sv,
  "OP_SREF_ALT"sv,
  "OP_SREF_S_PRI"sv,
  "OP_SREF_S_ALT"sv,
  "OP_STOR_I"sv,
  "OP_STRB_I"sv,
  "OP_LIDX"sv,
  "OP_LIDX_B"sv,
  "OP_IDXADDR"sv,
  "OP_IDXADDR_B"sv,
  "OP_ALIGN_PRI"sv,
  "OP_ALIGN_ALT"sv,
  "OP_LCTRL"sv,
  "OP_SCTRL"sv,
  "OP_MOVE_PRI"sv,
  "OP_MOVE_ALT"sv,
  "OP_XCHG"sv,
  "OP_PUSH_PRI"sv,
  "OP_PUSH_ALT"sv,
  "OP_PUSH_R"sv,
  "OP_PUSH_C"sv,
  "OP_PUSH"sv,
  "OP_PUSH_S"sv,
  "OP_P"sv"OP_PRI"sv,
  "OP_P"sv"OP_ALT"sv,
  "OP_STACK"sv,
  "OP_HEAP"sv,
  "OP_PROC"sv,
  "OP_RET"sv,
  "OP_RETN"sv,
  "OP_CALL"sv,
  "OP_CALL_PRI"sv,
  "OP_JUMP"sv,
  "OP_JREL"sv,
  "OP_JZER"sv,
  "OP_JNZ"sv,
  "OP_JEQ"sv,
  "OP_JNEQ"sv,
  "OP_JLESS"sv,
  "OP_JLEQ"sv,
  "OP_JGRTR"sv,
  "OP_JGEQ"sv,
  "OP_JSLESS"sv,
  "OP_JSLEQ"sv,
  "OP_JSGRTR"sv,
  "OP_JSGEQ"sv,
  "OP_SHL"sv,
  "OP_SHR"sv,
  "OP_SSHR"sv,
  "OP_SHL_C_PRI"sv,
  "OP_SHL_C_ALT"sv,
  "OP_SHR_C_PRI"sv,
  "OP_SHR_C_ALT"sv,
  "OP_SMUL"sv,
  "OP_SDIV"sv,
  "OP_SDIV_ALT"sv,
  "OP_UMUL"sv,
  "OP_UDIV"sv,
  "OP_UDIV_ALT"sv,
  "OP_ADD"sv,
  "OP_SUB"sv,
  "OP_SUB_ALT"sv,
  "OP_AND"sv,
  "OP_OR"sv,
  "OP_XOR"sv,
  "OP_NOT"sv,
  "OP_NEG"sv,
  "OP_INVERT"sv,
  "OP_ADD_C"sv,
  "OP_SMUL_C"sv,
  "OP_ZERO_PRI"sv,
  "OP_ZERO_ALT"sv,
  "OP_ZERO"sv,
  "OP_ZERO_S"sv,
  "OP_SIGN_PRI"sv,
  "OP_SIGN_ALT"sv,
  "OP_EQ"sv,
  "OP_NEQ"sv,
  "OP_LESS"sv,
  "OP_LEQ"sv,
  "OP_GRTR"sv,
  "OP_GEQ"sv,
  "OP_SLESS"sv,
  "OP_SLEQ"sv,
  "OP_SGRTR"sv,
  "OP_SGEQ"sv,
  "OP_EQ_C_PRI"sv,
  "OP_EQ_C_ALT"sv,
  "OP_INC_PRI"sv,
  "OP_INC_ALT"sv,
  "OP_INC"sv,
  "OP_INC_S"sv,
  "OP_INC_I"sv,
  "OP_DEC_PRI"sv,
  "OP_DEC_ALT"sv,
  "OP_DEC"sv,
  "OP_DEC_S"sv,
  "OP_DEC_I"sv,
  "OP_MOVS"sv,
  "OP_CMPS"sv,
  "OP_FILL"sv,
  "OP_HALT"sv,
  "OP_BOUNDS"sv,
  "OP_SYSREQ_PRI"sv,
  "OP_SYSREQ_C"sv,
  "OP_FILE"sv,
  "OP_LINE"sv,
  "OP_SYMBOL"sv,
  "OP_SRANGE"sv,
  "OP_JUMP_PRI"sv,
  "OP_SWITCH"sv,
  "OP_CASETBL"sv,
  "OP_SWAP_PRI"sv,
  "OP_SWAP_ALT"sv,
  "OP_PUSH_ADR"sv,
  "OP_NOP"sv,
  "OP_SYSREQ_N"sv,
  "OP_SYMTAG"sv,
  "OP_BREAK"sv,
  "OP_PUSH2_C"sv,
  "OP_PUSH2"sv,
  "OP_PUSH2_S"sv,
  "OP_PUSH2_ADR"sv,
  "OP_PUSH3_C"sv,
  "OP_PUSH3"sv,
  "OP_PUSH3_S"sv,
  "OP_PUSH3_ADR"sv,
  "OP_PUSH4_C"sv,
  "OP_PUSH4"sv,
  "OP_PUSH4_S"sv,
  "OP_PUSH4_ADR"sv,
  "OP_PUSH5_C"sv,
  "OP_PUSH5"sv,
  "OP_PUSH5_S"sv,
  "OP_PUSH5_ADR"sv,
  "OP_LOAD_BOTH"sv,
  "OP_LOAD_S_BOTH"sv,
  "OP_CONST"sv,
  "OP_CONST_S"sv,
  "OP_SYSREQ_D"sv,
  "OP_SYSREQ_ND"sv
};

#endif // !AMXOPCODE_H